{% set version = "0.0.6" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-ccdralgorithm
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/ccdrAlgorithm_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/ccdrAlgorithm/ccdrAlgorithm_{{ version }}.tar.gz
  sha256: e55e2b9a4cc39442e2621b2131f1ffba330ced0fa8fe12ae750340c0b5188b5f

build:
  number: 3
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}        # [not win]
    - {{ stdlib("c") }}          # [not win]
    - {{ compiler('cxx') }}      # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ stdlib("m2w64_c") }}          # [win]
    - {{ compiler('m2w64_cxx') }}      # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-rcpp >=0.11.0
    - r-sparsebnutils >=0.0.5
  run:
    - r-base
    - r-rcpp >=0.11.0
    - r-sparsebnutils >=0.0.5

test:
  commands:
    - $R -e "library('ccdrAlgorithm')"           # [not win]
    - "\"%R%\" -e \"library('ccdrAlgorithm')\""  # [win]

about:
  home: https://github.com/itsrainingdata/ccdrAlgorithm
  license: GPL-2.0-or-later
  summary: Implementation of the CCDr (Concave penalized Coordinate Descent with reparametrization) structure learning algorithm as described in Aragam and Zhou (2015) <http://www.jmlr.org/papers/v16/aragam15a.html>. This is a fast, score-based method for learning Bayesian networks that uses sparse regularization and block-cyclic
    coordinate descent.
  license_family: GPL3
  license_file: {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2

extra:
  recipe-maintainers:
    - conda-forge/r
