travis:
  secure:
    BINSTAR_TOKEN: gbQNwBKA1fkZrscEsDwlxdN5BGvyWROUeSknkfoRmWdKd2SMT8ZK6GkR7odzV3G5s/z99xgEHq1kwuiSnQs4sPH0yq7y1qS2SaFlOlQ9EkyPqt/F/QiLfC8Z5ZELr++TmrpmjoxsnYA6QbOHNbdtkQIiLhmijLIuPWZD9gQdW9gvwW9pCsIZy+PQqxC9xwlTzwSLjev1Xa2Glv1F1iA4Rpkk9GBnp3ZKUSV6R763EC1vK0KbaIwJO9yGBQo3Gxm2YrVZjByUvh5Vpa/UaWVMjemyF9bggJiMuFyYRLV8Rcq7zTRQPXvXKn5qsBDaZcVvoCDkh+EWLcD0m1+52ZVx1JodQSmOfpBAkE+E+G3h1bICxue36Po5adM9d0UTyQrp7z/PhA12hlulGTEdRBZP7jVyrGJzr9wFEwhRVdhAx1Jd0BD45j+DAatunz49bc9TMibNMB922QfuT5s99OUg3XlgU5aD75uu3AFMQTB/jFhBIHkXHwgawd9OCCKU+xOgKxF2pZ1dUS0LeNvwgqB8zkWsfAzYIkQbpgFQdi9urZP7H+oPz/mvXTVJQ/qX7Pm3cD5eHTDRN9HSm86/zI6O8wVQF1+ZomEqFn+sLRfZGHFc0I1rbeGs89GUXMmT45CKyzCwUi/yKK5C2cwGdBaKaOBMqGc6jyGnr/QTaKsSJeM=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
